Forum/Models/Theme.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Models
{
    public class Theme
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime DateTime { get; set; }
        public int MessageCount { get; set; }

        [ForeignKey("ApplicationUser")]
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

        public List<Message> Messages { get; set; }
    }
}
/*название
описание
автор
дата
ответы
количество ответов
лайки*/

Forum/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Forum.Data;
using Forum.Models;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;

namespace Forum.Controllers
{
    public class MessagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public MessagesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Messages
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Messages.Include(m => m.Theme).Include(m => m.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .Include(m => m.Theme)
                .Include(m => m.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // GET: Messages/Create
        public IActionResult Create()
        {
            ViewData["ThemeId"] = new SelectList(_context.Themes, "Id", "Id");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       
        public async Task<string> Create(int postid, string userId, string content)
        {
            var theme = _context.Themes.FirstOrDefault(p => p.Id == postid);
            Message data = new Message()
            {
                ThemeId = postid,
                UserId = userId,
                DescriptionMessage = content,
                DateTimeMessage = DateTime.Now
            };
            if (ModelState.IsValid)
            {
                theme.MessageCount = theme.MessageCount + 1;
                _context.Update(theme);
                _context.Add(data);

                await _context.SaveChangesAsync();

            }

            return JsonConvert.SerializeObject(data,
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        }

        // GET: Messages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages.SingleOrDefaultAsync(m => m.Id == id);
            if (message == null)
            {
                return NotFound();
            }
            ViewData["ThemeId"] = new SelectList(_context.Themes, "Id", "Id", message.ThemeId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", message.UserId);
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DescriptionMessage,DateTimeMessage,UserId,ThemeId")] Message message)
        {
            if (id != message.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(message);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MessageExists(message.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ThemeId"] = new SelectList(_context.Themes, "Id", "Id", message.ThemeId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", message.UserId);
            return View(message);
        }

        // GET: Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .Include(m => m.Theme)
                .Include(m => m.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var message = await _context.Messages.SingleOrDefaultAsync(m => m.Id == id);
            _context.Messages.Remove(message);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MessageExists(int id)
        {
            return _context.Messages.Any(e => e.Id == id);
        }
    }
}

Forum/Controllers/ThemesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Forum.Data;
using Forum.IndexViewModel;
using Forum.Models;
using Microsoft.AspNetCore.Identity;

namespace Forum.Controllers
{
    public class ThemesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ThemesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Themes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Themes.Include(t => t.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Themes/Details/5
        public async Task<IActionResult> Details(int? id, int page = 1)
        {

            if (id == null)
            {
                return NotFound();
            }

            var theme = await _context.Themes
                .Include(t => t.User).Include(t => t.Messages)
                .SingleOrDefaultAsync(m => m.Id == id);
            

            IQueryable<Message> messages = _context.Messages.Where(p => p.ThemeId == id).OrderBy(p => p.DateTimeMessage);
            int pageSize = 3;
            var count = await messages.CountAsync();
            var items = await messages.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            ViewBag.PageViewModel = pageViewModel;
            ViewBag.Answers = items;
            if (theme == null)
            {
                return NotFound();
            }

            return View(theme);
        }

        // GET: Themes/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Themes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Theme theme, IndexViewTheme indexViewTheme)
        {
            var user = await _userManager.GetUserAsync(User);
            theme.DateTime = DateTime.Now;
            theme.MessageCount = 0;
            theme.UserId = user.Id;
            theme.Description = indexViewTheme.Description;
            theme.Name = indexViewTheme.Name;

            if (ModelState.IsValid)
            {
                _context.Add(theme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", theme.UserId);
            return View(theme);
        }

        // GET: Themes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theme = await _context.Themes.SingleOrDefaultAsync(m => m.Id == id);
            if (theme == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", theme.UserId);
            return View(theme);
        }

        // POST: Themes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,DateTime,MessageCount,UserId")] Theme theme)
        {
            if (id != theme.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(theme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ThemeExists(theme.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", theme.UserId);
            return View(theme);
        }

        // GET: Themes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theme = await _context.Themes
                .Include(t => t.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (theme == null)
            {
                return NotFound();
            }

            return View(theme);
        }

        // POST: Themes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var theme = await _context.Themes.SingleOrDefaultAsync(m => m.Id == id);
            _context.Themes.Remove(theme);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ThemeExists(int id)
        {
            return _context.Themes.Any(e => e.Id == id);
        }
    }
}

Forum/Views/Themes/Create.cshtml
@using Forum.IndexViewModel
@model Forum.IndexViewModel.IndexViewTheme
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Theme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Forum/Views/Themes/Delete.cshtml
@model Forum.Models.Theme

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Theme</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MessageCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MessageCount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Forum/Views/Themes/Details.cshtml
@model Forum.Models.Theme

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Theme</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Автор
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Описание
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            Дата создания
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt>
            Сообщений
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MessageCount)
        </dd>
    </dl>
</div>


<div id="comments-@Model.Id">
   
        @foreach (var message in ViewBag.Answers)
        {
            <table class="table">
                <thead>
                    <tr>

                        <th>
                            Фото
                        </th>
                        <th>
                            Автор
                        </th>

                        <th>
                            Сообщение
                        </th>

                        <th>
                            Дата создания
                        </th>
                        <th>
                            Likes
                        </th>
                        <th>
                            DiseLike
                        </th>

                    </tr>
                </thead>
                <tbody>
                    <tr>

                        <td>
                            <img src="~/@message.User.Avatar" width="100" height="100" />
                        </td>
                        <td>
                            @message.User.Name
                        </td>
                        <td>
                            @message.DescriptionMessage
                        </td>
                        <td>
                            @message.DateTimeMessage
                        </td>
                        <td>
                            @message.LikeCount
                        </td>
                        <td>
                            @message.DiseLikeCount
                        </td>
                    </tr>
                </tbody>
            </table>


        }
    
</div>



<div id="postdiv-@Model.Id" id="postdiv">
    <textarea id="posttext-@Model.Id"></textarea>
    <input type="button" id="postComment" onclick="sendComment('@Model.Id', '@Model.User.Id')" value="Отправить" />
</div>
<div>
    <input type="button" value="Previouse" />
    <input type="button" value="Next" />
    <a asp-action="Index">Back to List</a>
</div>
@if (ViewBag.PageViewModel.HasPreviousPage)
{
    <a asp-action="Details"
       asp-route-page="@(ViewBag.PageViewModel.PageNumber - 1)"
       class="btn btn-default btn">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (ViewBag.PageViewModel.HasNextPage)
{
    <a asp-action="Details"
       asp-route-page="@(ViewBag.PageViewModel.PageNumber + 1)"
       class="btn btn-default btn">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}
@section Scripts
    {
    <script>

        function sendComment(postId, userId) {
            $.ajax({
                url: '@Url.Action("Create", "Messages")',
                type: 'POST',
                data: { 'postId': postId, 'userId': userId, 'content': $('#posttext-' + postId).val() },
                success: function fill(data) {
                    $('#comments-' + postId).append("<div>" + JSON.parse(data).DescriptionMessage + " |  " + JSON.parse(data).DateTimeMessage +
                        " |  " + JSON.parse(data).user + "</div>");

                }


            });
        }
    </script>
}

Forum/Views/Themes/Edit.cshtml
@model Forum.Models.Theme

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Theme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MessageCount" class="control-label"></label>
                <input asp-for="MessageCount" class="form-control" />
                <span asp-validation-for="MessageCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Forum/Views/Themes/Index.cshtml
@model IEnumerable<Forum.Models.Theme>

@{
    ViewData["Title"] = "Index";
}

<h2>Темы</h2>
@if (User.Identity.IsAuthenticated)
{
<p>
    <a asp-action="Create">Создать новую тему</a>
</p>
}
<table class="table">
    <thead>
        <tr>
                <th>
                    Название
                </th>
                
                <th>
                    Автор
                </th>
                <th>
                   Количество сообщениЙ в теме
                </th>
                <th>
                    Дата создания
                </th>
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MessageCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>